# Generated by Django 5.1 on 2024-10-28 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='like',
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
