# Generated by Django 5.1 on 2024-10-28 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_posts_like_posts_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
